export const USER_POSTS_FETCH_REQUESTED = 'USER_POSTS_FETCH_REQUESTED'
export const USER_POSTS_FETCH_SUCCEEDED = 'USER_POSTS_FETCH_SUCCEEDED'
export const USER_POSTS_FETCH_FAILED = 'USER_POSTS_FETCH_FAILED'
