export const USER_POSTS_FETCH_REQUESTED = 'USER_POSTS_FETCH_REQUESTED'
export const USER_POSTS_FETCH_SUCCEEDED = 'USER_POSTS_FETCH_SUCCEEDED'
export const USER_POSTS_FETCH_FAILED = 'USER_POSTS_FETCH_FAILED'

export const SAVE_USER_POSTS = 'SAVE_USER_POSTS'
export const SAVE_USER_ALBUMS = 'SAVE_USER_ALBUMS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT = 'LOGOUT'
export const STOP_LOGING_PENDING = 'STOP_LOGING_PENDING'
